services:
  rvc:
    build: .
    container_name: rvc

    ports:
      - "7865:7865"

    volumes:
      - ./assets/weights:/app/assets/weights
      - ./assets/indices:/app/assets/indices
      - ./logs:/app/logs
      - ./datasets:/app/datasets

    restart: unless-stopped